// Asset types and enums
export enum AssetType {
  EQUIPMENT = "equipment",
  VEHICLE = "vehicle",
  BUILDING = "building",
  FURNITURE = "furniture",
  TOOL = "tool",
  OTHER = "other",
}

export enum AssetCondition {
  EXCELLENT = "excellent",
  GOOD = "good",
  FAIR = "fair",
  POOR = "poor",
  CRITICAL = "critical",
}

export interface AssetData {
  id: string;
  type: AssetType;
  name: string;
  location?: string;
  condition: AssetCondition;
  notes?: string;
  qrTagId?: string;
  createdAt: Date;
  updatedAt: Date;
  synced: boolean;
}

export interface CreateAssetData {
  type: AssetType;
  name: string;
  location?: string;
  condition: AssetCondition;
  notes?: string;
  qrTagId?: string;
}

export interface UpdateAssetData {
  type?: AssetType;
  name?: string;
  location?: string;
  condition?: AssetCondition;
  notes?: string;
  qrTagId?: string;
}

// Inspection types and enums
export interface InspectionData {
  id: string;
  assetId: string;
  inspector: string;
  description: string;
  score: number; // 1-10 scale from AI
  timestamp: Date;
  maintenanceNeeded: boolean;
  nextDue?: Date;
  createdAt: Date;
  updatedAt: Date;
  synced: boolean;
}

export interface CreateInspectionData {
  assetId: string;
  inspector: string;
  description: string;
  score?: number; // Will be generated by AI if not provided
  maintenanceNeeded?: boolean;
  nextDue?: Date;
}

export interface UpdateInspectionData {
  inspector?: string;
  description?: string;
  score?: number;
  maintenanceNeeded?: boolean;
  nextDue?: Date;
}

// Utility types
export type SortOrder = "asc" | "desc";

export interface AssetFilters {
  type?: AssetType;
  condition?: AssetCondition;
  location?: string;
  searchQuery?: string;
}

export interface AssetSortOptions {
  field: "name" | "type" | "condition" | "createdAt" | "updatedAt";
  order: SortOrder;
}
